version: '3'
services:

  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: xEjg7922vXZp
      MYSQL_DATABASE: autobiddata
      MYSQL_USER: admin
      MYSQL_PASSWORD: 3nW7Y6nsxVKh
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - autobidnet

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - nginx_conf:/etc/nginx
    depends_on:
      - mysql
    networks:
      - autobidnet

volumes:
  mysql_data:
  nginx_conf:

networks:
  autobidnet:
